# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0 # Use a version consistent with pyproject.toml
    hooks:
    -   id: mypy
        args:
            - --disable-error-code=unused-ignore
        files: ^(backend/|frontend/)
        # Optionally exclude files/directories if needed:
        exclude: (^|.*/)test # Exclude any file/dir starting with 'test' in any part of the path
        # Specify additional dependencies if mypy needs them for your project
        additional_dependencies: [
            'pydantic',
            'types-requests',
            'types-python-jose',
            # Add stubs for google APIs if available (often not)
            # Add stubs for other missing libs like fastapi, bcrypt, jwt, dotenv, langgraph, pytest
            'fastapi',
            'bcrypt',
            'python-jose[cryptography]', # Need extras for crypto
            'python-dotenv',
            'langgraph',
            'pytest',
            'google-api-python-client', # Might provide some google stubs
            'types-pyjwt', # Stubs for PyJWT
            'pandas-stubs>=2.2.3.250308',
            'types-cachetools>=5.5.0.20240820',
            "types-defusedxml>=0.7.0.20240218",
            # 'types-Flask>=3.0.0.20240118', # Removed due to sync issues
            "types-httplib2>=0.22.0.20241221",
            "types-protobuf>=5.29.1.20250315",
            "types-psutil>=7.0.0.20250218",
            "types-pycurl>=7.45.6.20250309",
            "types-pygments>=2.19.0.20250305",
            "types-pyjwt>=1.7.1",
            "types-pyopenssl>=24.1.0.20240722",
            "types-python-jose>=3.4.0.20250224",
            "types-pyyaml>=6.0.12.20250326",
            "types-requests>=2.32.0.20250328",
            "types-tqdm>=4.67.0.20250319",
            ]

-   repo: https://github.com/pylint-dev/pylint
    rev: v3.1.0 # Or choose a specific version
    hooks:
    -   id: pylint
        args:
          - --rcfile=pyproject.toml # Assuming pylint config is in pyproject.toml
        files: ^(backend/|frontend/) # Adjust pattern as needed
        # exclude: # Add excludes if necessary

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        # Optionally add stages if you only want it to run on commit, not push, etc.
        # stages: [commit]