# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1 # Use a specific version of mypy hook
    hooks:
    -   id: mypy
        args: [--strict] # Start with strict checking
        # Optionally exclude files/directories if needed:
        # exclude: ^(docs/|tests/|frontend/)
        # Specify additional dependencies if mypy needs them for your project
        # additional_dependencies: ['pydantic', 'fastapi']